### ISSUE TITLE
GitHub Actions CI - Ruby v3.3.1 failing

### ISSUE THREAD

**Issue by ewlarson** [bplmaps/blacklight-allmaps#42]
Locally, our test suite with Ruby v3.3.0 and v3.3.1 passes all green. However, on GitHub Actions / CI, Ruby is now defaulting to v3.3.1 (recently released) and failing with an odd error...

```
Done generating test app
/opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/resolver.rb:336:in `raise_not_found!': Could not find gems matching 'blacklight_allmaps (= 0.2.0)' valid for all resolution platforms () in source at `/home/runner/work/blacklight-allmaps/blacklight-allmaps`. (Bundler::GemNotFound)
```

Even v3.3.0 test builds/runs that passed two weeks ago are now failing, as they are being re-ran with v3.3.1. Below, see that "Attempt 1" is green and "Attempt 2" fails:

![Screenshot 2024-04-24 at 10 20 56 AM](https://github.com/bplmaps/blacklight-allmaps/assets/69827/10de43f7-4d5f-45fd-a8a1-7d2803545e6c)

Troubleshooting.

**Comment by ewlarson** [comment]
Could try downgrading rubygems version used by CI:
https://github.com/ruby/setup-ruby/blob/master/action.yml

Set the `rubygems` arg.

**Comment by ewlarson** [comment]
Can't downgrade `rubygems` as it ignores your stated version if there is a newer.

**Comment by ewlarson** [comment]
Forcing a platform into the bundle for the CI workflow resolved this issue.

```yml
...
      - name: Lock platform version
        run: bundle lock --add-platform ruby
      - name: Install dependencies
        run: bundle install
...
```
